name: Bug Report
description: Create a bug report.
labels:
  - type::bug
body:
  - type: markdown
    attributes:
      value: |
        Processing bug reports is time consuming so please fill out the following form as completely as possible. **The more complete you are the more likely we can provide a speedier response.**

        > ⚠️ Reports that are incomplete or missing information will simply be closed.

        Since there are already a lot of open issues, please take a moment to search existing ones to see if your bug has already been reported. If you find something related, please upvote that report and provide additional details as necessary.

        > 💐 Thanks for helping to make Conda better! We would be unable to do the things we do without our community!
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I added a descriptive title
          required: true
        - label: I searched open reports and couldn't find a duplicate
          required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What should have happened instead? Please provide as many details as possible. The more information provided the more likely we are able to replicate your problem and offer a solution.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Conda Info
      description: |
        Let's collect some basic information about your conda install.

        Please run the following command from your command line and paste the output below.

        ```bash
        conda info
        ```
      render: shell
  - type: textarea
    id: config
    attributes:
      label: Conda Config
      description: |
        Let's collect any customizations you may have for your conda install.

        Please run the following command from your command line and paste the output below.

        ```bash
        conda config --show-sources
        ```
      render: shell
  - type: textarea
    id: list
    attributes:
      label: Conda list
      description: |
        The packages installed into your environment can offer clues as to the problem you are facing.

        Please ensure you have activated the environment within which you are encountering this bug and run the following command from your command line and paste the output below.

        ```bash
        conda list --show-channel-urls
        ```
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information (or screenshots) that you think would be valuable.
